global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'backend1'
    static_configs:
      - targets: ['backend1:3000']
    metrics_path: '/metrics'

  - job_name: 'backend2'
    static_configs:
      - targets: ['backend2:3000']
    metrics_path: '/metrics' 